FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ./src ./
COPY ./Directory.Build.props ./
RUN dotnet publish -c Release -o /publish --self-contained true -v normal -p:PublishTrimmed=true -p:PublishSingleFile=true -r linux-x64 ./api/Laobian.Api.csproj

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /publish ./
RUN apt update -y && apt install git -y && chmod +x laobian.api
ENV TZ=Asia/Shanghai

ENTRYPOINT ["./laobian.api"]