FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ./src ./
COPY ./Directory.Build.props ./
RUN dotnet publish \
    -c Release \
    -o /publish \
    -v normal \
    ./api/Laobian.Api.csproj

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /publish ./
RUN apt install git -y
ENV TZ=Asia/Shanghai

ENTRYPOINT ["dotnet", "laobian.api.dll"]